/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://evbg7667cbeqxbllx7ld2r756i.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3mphsap4ujfrfdgcawulk67fdu",
    "aws_cognito_identity_pool_id": "ap-south-1:89f590ba-4388-43b7-950a-c9aa9adf65fb",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_PpCnmxa8W",
    "aws_user_pools_web_client_id": "6q7dqj3jnq21irkgmls98lc7gj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
